// Mocks generated by Mockito 5.4.6 from annotations
// in medico24/test/core/repositories/pharmacy_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i5;
import 'package:medico24/core/api/models/pharmacy_model.dart' as _i2;
import 'package:medico24/core/api/services/pharmacy_api_service.dart' as _i7;
import 'package:medico24/core/database/database.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePharmacyModel_0 extends _i1.SmartFake implements _i2.PharmacyModel {
  _FakePharmacyModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePharmacyHoursModel_1 extends _i1.SmartFake
    implements _i2.PharmacyHoursModel {
  _FakePharmacyHoursModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_2 extends _i1.SmartFake
    implements _i3.MigrationStrategy {
  _FakeMigrationStrategy_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AccessibilitySettingsTable_3 extends _i1.SmartFake
    implements _i4.$AccessibilitySettingsTable {
  _Fake$AccessibilitySettingsTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SavedAddressesTable_4 extends _i1.SmartFake
    implements _i4.$SavedAddressesTable {
  _Fake$SavedAddressesTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecentLocationsTable_5 extends _i1.SmartFake
    implements _i4.$RecentLocationsTable {
  _Fake$RecentLocationsTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CurrentLocationTable_6 extends _i1.SmartFake
    implements _i4.$CurrentLocationTable {
  _Fake$CurrentLocationTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppointmentsTable_7 extends _i1.SmartFake
    implements _i4.$AppointmentsTable {
  _Fake$AppointmentsTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CachedUserTable_8 extends _i1.SmartFake
    implements _i4.$CachedUserTable {
  _Fake$CachedUserTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CachedPharmaciesTable_9 extends _i1.SmartFake
    implements _i4.$CachedPharmaciesTable {
  _Fake$CachedPharmaciesTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_10 extends _i1.SmartFake
    implements _i4.$AppDatabaseManager {
  _Fake$AppDatabaseManager_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_11 extends _i1.SmartFake
    implements _i3.GeneratedDatabase {
  _FakeGeneratedDatabase_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_12 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_13 extends _i1.SmartFake
    implements _i3.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_14 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_15 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_16 extends _i1.SmartFake
    implements _i5.StreamQueryStore {
  _FakeStreamQueryStore_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_17 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_18 extends _i1.SmartFake implements _i3.Migrator {
  _FakeMigrator_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_19<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_20<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_21<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_22<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_23<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_24<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_25<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_26<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_27 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PharmacyApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPharmacyApiService extends _i1.Mock
    implements _i7.PharmacyApiService {
  MockPharmacyApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.PharmacyModel>> getPharmacies({
    int? skip = 0,
    int? limit = 20,
    double? latitude,
    double? longitude,
    double? radiusKm = 10.0,
    bool? isActive,
    bool? isVerified,
    bool? supportsDelivery,
    bool? supportsPickup,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPharmacies, [], {
              #skip: skip,
              #limit: limit,
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #isActive: isActive,
              #isVerified: isVerified,
              #supportsDelivery: supportsDelivery,
              #supportsPickup: supportsPickup,
            }),
            returnValue: _i6.Future<List<_i2.PharmacyModel>>.value(
              <_i2.PharmacyModel>[],
            ),
          )
          as _i6.Future<List<_i2.PharmacyModel>>);

  @override
  _i6.Future<List<_i2.PharmacyModel>> searchPharmaciesNearby({
    required double? latitude,
    required double? longitude,
    double? radiusKm = 10.0,
    int? skip = 0,
    int? limit = 20,
    bool? isActive,
    bool? isVerified,
    bool? supportsDelivery,
    bool? supportsPickup,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPharmaciesNearby, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #skip: skip,
              #limit: limit,
              #isActive: isActive,
              #isVerified: isVerified,
              #supportsDelivery: supportsDelivery,
              #supportsPickup: supportsPickup,
            }),
            returnValue: _i6.Future<List<_i2.PharmacyModel>>.value(
              <_i2.PharmacyModel>[],
            ),
          )
          as _i6.Future<List<_i2.PharmacyModel>>);

  @override
  _i6.Future<_i2.PharmacyModel> getPharmacyById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPharmacyById, [id]),
            returnValue: _i6.Future<_i2.PharmacyModel>.value(
              _FakePharmacyModel_0(
                this,
                Invocation.method(#getPharmacyById, [id]),
              ),
            ),
          )
          as _i6.Future<_i2.PharmacyModel>);

  @override
  _i6.Future<_i2.PharmacyModel> createPharmacy(
    _i2.PharmacyCreateRequest? pharmacy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPharmacy, [pharmacy]),
            returnValue: _i6.Future<_i2.PharmacyModel>.value(
              _FakePharmacyModel_0(
                this,
                Invocation.method(#createPharmacy, [pharmacy]),
              ),
            ),
          )
          as _i6.Future<_i2.PharmacyModel>);

  @override
  _i6.Future<_i2.PharmacyModel> updatePharmacy(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePharmacy, [id, updates]),
            returnValue: _i6.Future<_i2.PharmacyModel>.value(
              _FakePharmacyModel_0(
                this,
                Invocation.method(#updatePharmacy, [id, updates]),
              ),
            ),
          )
          as _i6.Future<_i2.PharmacyModel>);

  @override
  _i6.Future<void> deletePharmacy(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePharmacy, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.PharmacyHoursModel>> getPharmacyHours(
    String? pharmacyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPharmacyHours, [pharmacyId]),
            returnValue: _i6.Future<List<_i2.PharmacyHoursModel>>.value(
              <_i2.PharmacyHoursModel>[],
            ),
          )
          as _i6.Future<List<_i2.PharmacyHoursModel>>);

  @override
  _i6.Future<_i2.PharmacyHoursModel> addPharmacyHours(
    String? pharmacyId,
    _i2.PharmacyHoursCreateRequest? hours,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPharmacyHours, [pharmacyId, hours]),
            returnValue: _i6.Future<_i2.PharmacyHoursModel>.value(
              _FakePharmacyHoursModel_1(
                this,
                Invocation.method(#addPharmacyHours, [pharmacyId, hours]),
              ),
            ),
          )
          as _i6.Future<_i2.PharmacyHoursModel>);

  @override
  _i6.Future<void> deletePharmacyHours(String? pharmacyId, int? dayOfWeek) =>
      (super.noSuchMethod(
            Invocation.method(#deletePharmacyHours, [pharmacyId, dayOfWeek]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i4.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i3.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_2(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i3.MigrationStrategy);

  @override
  _i4.$AccessibilitySettingsTable get accessibilitySettings =>
      (super.noSuchMethod(
            Invocation.getter(#accessibilitySettings),
            returnValue: _Fake$AccessibilitySettingsTable_3(
              this,
              Invocation.getter(#accessibilitySettings),
            ),
          )
          as _i4.$AccessibilitySettingsTable);

  @override
  _i4.$SavedAddressesTable get savedAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#savedAddresses),
            returnValue: _Fake$SavedAddressesTable_4(
              this,
              Invocation.getter(#savedAddresses),
            ),
          )
          as _i4.$SavedAddressesTable);

  @override
  _i4.$RecentLocationsTable get recentLocations =>
      (super.noSuchMethod(
            Invocation.getter(#recentLocations),
            returnValue: _Fake$RecentLocationsTable_5(
              this,
              Invocation.getter(#recentLocations),
            ),
          )
          as _i4.$RecentLocationsTable);

  @override
  _i4.$CurrentLocationTable get currentLocation =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocation),
            returnValue: _Fake$CurrentLocationTable_6(
              this,
              Invocation.getter(#currentLocation),
            ),
          )
          as _i4.$CurrentLocationTable);

  @override
  _i4.$AppointmentsTable get appointments =>
      (super.noSuchMethod(
            Invocation.getter(#appointments),
            returnValue: _Fake$AppointmentsTable_7(
              this,
              Invocation.getter(#appointments),
            ),
          )
          as _i4.$AppointmentsTable);

  @override
  _i4.$CachedUserTable get cachedUser =>
      (super.noSuchMethod(
            Invocation.getter(#cachedUser),
            returnValue: _Fake$CachedUserTable_8(
              this,
              Invocation.getter(#cachedUser),
            ),
          )
          as _i4.$CachedUserTable);

  @override
  _i4.$CachedPharmaciesTable get cachedPharmacies =>
      (super.noSuchMethod(
            Invocation.getter(#cachedPharmacies),
            returnValue: _Fake$CachedPharmaciesTable_9(
              this,
              Invocation.getter(#cachedPharmacies),
            ),
          )
          as _i4.$CachedPharmaciesTable);

  @override
  _i4.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_10(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i4.$AppDatabaseManager);

  @override
  Iterable<_i3.TableInfo<_i3.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i3.TableInfo<_i3.Table, Object?>>[],
          )
          as Iterable<_i3.TableInfo<_i3.Table, Object?>>);

  @override
  List<_i3.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i3.DatabaseSchemaEntity>[],
          )
          as List<_i3.DatabaseSchemaEntity>);

  @override
  _i3.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_11(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i3.GeneratedDatabase);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_12(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_13(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i3.StreamQueryUpdateRules);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_14(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i8.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_15(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i5.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_16(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i5.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_17(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i6.Future<_i4.AccessibilitySetting?> getAccessibilitySettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessibilitySettings, []),
            returnValue: _i6.Future<_i4.AccessibilitySetting?>.value(),
          )
          as _i6.Future<_i4.AccessibilitySetting?>);

  @override
  _i6.Future<int> updateAccessibilitySettings({
    required String? hearingLevel,
    required String? visionLevel,
    required String? mobilityLevel,
    required bool? isOlderPerson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccessibilitySettings, [], {
              #hearingLevel: hearingLevel,
              #visionLevel: visionLevel,
              #mobilityLevel: mobilityLevel,
              #isOlderPerson: isOlderPerson,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i4.SavedAddressesData>> getAllSavedAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSavedAddresses, []),
            returnValue: _i6.Future<List<_i4.SavedAddressesData>>.value(
              <_i4.SavedAddressesData>[],
            ),
          )
          as _i6.Future<List<_i4.SavedAddressesData>>);

  @override
  _i6.Future<int> addSavedAddress({
    required String? title,
    required String? address,
    required String? city,
    double? latitude,
    double? longitude,
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSavedAddress, [], {
              #title: title,
              #address: address,
              #city: city,
              #latitude: latitude,
              #longitude: longitude,
              #isDefault: isDefault,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteSavedAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSavedAddress, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i4.RecentLocation>> getRecentLocations({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentLocations, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i4.RecentLocation>>.value(
              <_i4.RecentLocation>[],
            ),
          )
          as _i6.Future<List<_i4.RecentLocation>>);

  @override
  _i6.Future<int> addRecentLocation({
    required String? address,
    required String? city,
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addRecentLocation, [], {
              #address: address,
              #city: city,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> clearOldRecentLocations({int? keepCount = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#clearOldRecentLocations, [], {
              #keepCount: keepCount,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.CurrentLocationData?> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i6.Future<_i4.CurrentLocationData?>.value(),
          )
          as _i6.Future<_i4.CurrentLocationData?>);

  @override
  _i6.Future<int> updateCurrentLocation({
    required String? title,
    required String? address,
    required String? city,
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentLocation, [], {
              #title: title,
              #address: address,
              #city: city,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i4.Appointment>> getAllAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAppointments, []),
            returnValue: _i6.Future<List<_i4.Appointment>>.value(
              <_i4.Appointment>[],
            ),
          )
          as _i6.Future<List<_i4.Appointment>>);

  @override
  _i6.Future<List<_i4.Appointment>> getAppointmentsByDateRange(
    DateTime? fromDate,
    DateTime? toDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsByDateRange, [fromDate, toDate]),
            returnValue: _i6.Future<List<_i4.Appointment>>.value(
              <_i4.Appointment>[],
            ),
          )
          as _i6.Future<List<_i4.Appointment>>);

  @override
  _i6.Future<int> insertAppointment(_i4.AppointmentsCompanion? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#insertAppointment, [appointment]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> insertAppointments(
    List<_i4.AppointmentsCompanion>? appointmentList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertAppointments, [appointmentList]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> updateAppointment(_i4.Appointment? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointment, [appointment]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteAppointment(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppointment, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> clearAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#clearAppointments, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.CachedUserData?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i6.Future<_i4.CachedUserData?>.value(),
          )
          as _i6.Future<_i4.CachedUserData?>);

  @override
  _i6.Future<int> insertOrUpdateCachedUser(_i4.CachedUserCompanion? user) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrUpdateCachedUser, [user]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> clearCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.CachedPharmacy>> getAllCachedPharmacies() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCachedPharmacies, []),
            returnValue: _i6.Future<List<_i4.CachedPharmacy>>.value(
              <_i4.CachedPharmacy>[],
            ),
          )
          as _i6.Future<List<_i4.CachedPharmacy>>);

  @override
  _i6.Future<List<_i4.CachedPharmacy>> getNearbyPharmacies(
    double? latitude,
    double? longitude,
    double? radiusKm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyPharmacies, [
              latitude,
              longitude,
              radiusKm,
            ]),
            returnValue: _i6.Future<List<_i4.CachedPharmacy>>.value(
              <_i4.CachedPharmacy>[],
            ),
          )
          as _i6.Future<List<_i4.CachedPharmacy>>);

  @override
  _i6.Future<_i4.CachedPharmacy?> getCachedPharmacyById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPharmacyById, [id]),
            returnValue: _i6.Future<_i4.CachedPharmacy?>.value(),
          )
          as _i6.Future<_i4.CachedPharmacy?>);

  @override
  _i6.Future<int> insertOrUpdateCachedPharmacy(
    _i4.CachedPharmaciesCompanion? pharmacy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrUpdateCachedPharmacy, [pharmacy]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> insertOrUpdateCachedPharmacies(
    List<_i4.CachedPharmaciesCompanion>? pharmacyList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrUpdateCachedPharmacies, [pharmacyList]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearCachedPharmacies() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedPharmacies, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i3.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_18(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i3.Migrator);

  @override
  _i6.Future<void> beforeOpen(
    _i3.QueryExecutor? executor,
    _i3.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
    _i5.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i6.Stream<T>.empty(),
          )
          as _i6.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i6.Stream<Set<_i3.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
    _i6.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_19<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i6.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_20<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_21<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_22<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_23<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_24<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_25<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i6.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_26<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_26<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i6.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_19<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_19<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> runWithInterceptor<T>(
    _i6.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_19<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_27(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_27(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
