# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

# Analyzer configuration
analyzer:
  # Exclude generated files and build directories
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated/**"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "**/*.mocks.dart"

  # Strong mode analysis
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  # Error severity configuration
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Treat TODO comments as info (not errors)
    todo: info
    # Treat deprecated member use as warnings
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: warning
    # Treat invalid annotations as errors
    invalid_annotation_target: ignore

  # Language settings
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # ========================================================================
    # Style Rules
    # ========================================================================
    # Prefer single quotes for strings
    prefer_single_quotes: true
    # Require trailing commas for better formatting
    require_trailing_commas: true
    # Always use package imports (package:medico24/...)
    always_use_package_imports: true
    # Sort constructor declarations before other members
    sort_constructors_first: true
    # Sort unnamed constructor declarations before named ones
    sort_unnamed_constructors_first: true
    # Always declare return types
    always_declare_return_types: true
    # Use const constructors when possible
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    # Avoid empty else statements
    avoid_empty_else: true
    # Always put required named parameters first
    always_put_required_named_parameters_first: true
    # Prefer collection literals
    prefer_collection_literals: true
    # Use if-null operators
    prefer_if_null_operators: true
    # Prefer is empty/is not empty
    prefer_is_empty: true
    prefer_is_not_empty: true
    # Use spread collections
    prefer_spread_collections: true
    # Prefer for elements to map from iterables
    prefer_for_elements_to_map_fromIterable: true
    # Prefer if elements in collections
    prefer_if_elements_to_conditional_expressions: true
    # Use adjacent strings
    prefer_adjacent_string_concatenation: true
    # Use interpolation
    prefer_interpolation_to_compose_strings: true
    # Avoid unnecessary containers
    avoid_unnecessary_containers: true
    # Use key in widget constructors
    use_key_in_widget_constructors: true
    # Prefer final fields
    prefer_final_fields: true
    # Prefer final in for each
    prefer_final_in_for_each: true
    # Prefer final locals
    prefer_final_locals: true
    # Use full hex values for color
    use_full_hex_values_for_flutter_colors: true
    # Sized box for whitespace
    sized_box_for_whitespace: true
    # Use colored box
    use_colored_box: true
    # Use decorated box
    use_decorated_box: true

    # ========================================================================
    # Error Prevention
    # ========================================================================
    # Avoid print statements in production
    avoid_print: true
    # Avoid relative lib imports
    avoid_relative_lib_imports: true
    # Avoid returning null for Future
    avoid_returning_null_for_future: true
    # Avoid slow async operations
    avoid_slow_async_io: true
    # Avoid types as parameter names
    avoid_types_as_parameter_names: true
    # Avoid web libraries outside web
    avoid_web_libraries_in_flutter: true
    # Cancel futures
    cancel_subscriptions: true
    # Close sinks
    close_sinks: true
    # Comment references
    comment_references: true
    # Control flow in finally
    control_flow_in_finally: true
    # Invariant booleans
    invariant_booleans: true
    # Literal only boolean expressions
    literal_only_boolean_expressions: true
    # No adjacent strings in list
    no_adjacent_strings_in_list: true
    # No duplicate case values
    no_duplicate_case_values: true
    # No logic in create state
    no_logic_in_create_state: true
    # Prefer void to null
    prefer_void_to_null: true
    # Test types in equals
    test_types_in_equals: true
    # Throw in finally
    throw_in_finally: true
    # Unnecessary statements
    unnecessary_statements: true
    # Unrelated type equality checks
    unrelated_type_equality_checks: true
    # Unsafe HTML
    unsafe_html: true
    # Use build context synchronously
    use_build_context_synchronously: true
    # Valid regexps
    valid_regexps: true

    # ========================================================================
    # Documentation
    # ========================================================================
    # Package API documentation
    package_api_docs: true
    # Public member API docs
    public_member_api_docs: false  # Set to true if you want to enforce docs on all public members

    # ========================================================================
    # Formatting (handled by dart format, but good to enforce)
    # ========================================================================
    # Curly braces in flow control structures
    curly_braces_in_flow_control_structures: true
    # Slash for doc comments
    slash_for_doc_comments: true
    # Unnecessary brace in string interps
    unnecessary_brace_in_string_interps: true
    # One member abstracts
    one_member_abstracts: false

    # ========================================================================
    # Performance
    # ========================================================================
    # Avoid function literals in foreach calls
    avoid_function_literals_in_foreach_calls: true
    # Use to and as list
    use_to_and_as_if_applicable: true

    # ========================================================================
    # Null Safety
    # ========================================================================
    # Always require non-null return values
    always_require_non_null_named_parameters: true
    # Avoid null checks on closures
    avoid_null_checks_in_equality_operators: true
    # Prefer null aware method calls
    prefer_null_aware_method_calls: true
    # Tighten type of initializing formals
    tighten_type_of_initializing_formals: true
    # Unnecessary null aware assignments
    unnecessary_null_aware_assignments: true
    # Unnecessary null checks
    unnecessary_null_checks: true
    # Unnecessary null in if null operators
    unnecessary_null_in_if_null_operators: true
    # Unnecessary nullable for final variable declarations
    unnecessary_nullable_for_final_variable_declarations: true

    # ========================================================================
    # Disabled Rules (with justification)
    # ========================================================================
    # Avoid dynamic calls - too strict for some use cases
    avoid_dynamic_calls: false
    # Lines longer than 80 chars - we use 100 char line length
    lines_longer_than_80_chars: false
    # Avoid catches without on clauses - sometimes necessary
    avoid_catches_without_on_clauses: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
