// Mocks generated by Mockito 5.4.6 from annotations
// in medico24/test/integration/offline_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:medico24/core/api/models/pharmacy_model.dart' as _i2;
import 'package:medico24/core/api/services/pharmacy_api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePharmacyModel_0 extends _i1.SmartFake implements _i2.PharmacyModel {
  _FakePharmacyModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePharmacyHoursModel_1 extends _i1.SmartFake
    implements _i2.PharmacyHoursModel {
  _FakePharmacyHoursModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PharmacyApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPharmacyApiService extends _i1.Mock
    implements _i3.PharmacyApiService {
  MockPharmacyApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PharmacyModel>> getPharmacies({
    int? skip = 0,
    int? limit = 20,
    double? latitude,
    double? longitude,
    double? radiusKm = 10.0,
    bool? isActive,
    bool? isVerified,
    bool? supportsDelivery,
    bool? supportsPickup,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPharmacies, [], {
              #skip: skip,
              #limit: limit,
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #isActive: isActive,
              #isVerified: isVerified,
              #supportsDelivery: supportsDelivery,
              #supportsPickup: supportsPickup,
            }),
            returnValue: _i4.Future<List<_i2.PharmacyModel>>.value(
              <_i2.PharmacyModel>[],
            ),
          )
          as _i4.Future<List<_i2.PharmacyModel>>);

  @override
  _i4.Future<List<_i2.PharmacyModel>> searchPharmaciesNearby({
    required double? latitude,
    required double? longitude,
    double? radiusKm = 10.0,
    int? skip = 0,
    int? limit = 20,
    bool? isActive,
    bool? isVerified,
    bool? supportsDelivery,
    bool? supportsPickup,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPharmaciesNearby, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #skip: skip,
              #limit: limit,
              #isActive: isActive,
              #isVerified: isVerified,
              #supportsDelivery: supportsDelivery,
              #supportsPickup: supportsPickup,
            }),
            returnValue: _i4.Future<List<_i2.PharmacyModel>>.value(
              <_i2.PharmacyModel>[],
            ),
          )
          as _i4.Future<List<_i2.PharmacyModel>>);

  @override
  _i4.Future<_i2.PharmacyModel> getPharmacyById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPharmacyById, [id]),
            returnValue: _i4.Future<_i2.PharmacyModel>.value(
              _FakePharmacyModel_0(
                this,
                Invocation.method(#getPharmacyById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.PharmacyModel>);

  @override
  _i4.Future<_i2.PharmacyModel> createPharmacy(
    _i2.PharmacyCreateRequest? pharmacy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPharmacy, [pharmacy]),
            returnValue: _i4.Future<_i2.PharmacyModel>.value(
              _FakePharmacyModel_0(
                this,
                Invocation.method(#createPharmacy, [pharmacy]),
              ),
            ),
          )
          as _i4.Future<_i2.PharmacyModel>);

  @override
  _i4.Future<_i2.PharmacyModel> updatePharmacy(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePharmacy, [id, updates]),
            returnValue: _i4.Future<_i2.PharmacyModel>.value(
              _FakePharmacyModel_0(
                this,
                Invocation.method(#updatePharmacy, [id, updates]),
              ),
            ),
          )
          as _i4.Future<_i2.PharmacyModel>);

  @override
  _i4.Future<void> deletePharmacy(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePharmacy, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.PharmacyHoursModel>> getPharmacyHours(
    String? pharmacyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPharmacyHours, [pharmacyId]),
            returnValue: _i4.Future<List<_i2.PharmacyHoursModel>>.value(
              <_i2.PharmacyHoursModel>[],
            ),
          )
          as _i4.Future<List<_i2.PharmacyHoursModel>>);

  @override
  _i4.Future<_i2.PharmacyHoursModel> addPharmacyHours(
    String? pharmacyId,
    _i2.PharmacyHoursCreateRequest? hours,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPharmacyHours, [pharmacyId, hours]),
            returnValue: _i4.Future<_i2.PharmacyHoursModel>.value(
              _FakePharmacyHoursModel_1(
                this,
                Invocation.method(#addPharmacyHours, [pharmacyId, hours]),
              ),
            ),
          )
          as _i4.Future<_i2.PharmacyHoursModel>);

  @override
  _i4.Future<void> deletePharmacyHours(String? pharmacyId, int? dayOfWeek) =>
      (super.noSuchMethod(
            Invocation.method(#deletePharmacyHours, [pharmacyId, dayOfWeek]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
